name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
     - vuejs

jobs:
  build:
    name: Build on node v10.16.2 and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js v10.16.2
      uses: actions/setup-node@v1
      with:
        node-version: 10.16.2
    - name: npm install and build
      run: |
        npm install
        npm run build
      env:
        CI: true
